### ISSUE TITLE
port to Python?

### ISSUE THREAD

**Issue by rsignell-usgs** [socib/glider_toolbox#5]
Do you know of any work or plans to port this processing to Python?

**Comment by cyrf0006** [comment]
Not that I am aware of, but if this comes a project I could be interested to contribute (but not to lead!).

**Comment by richardsc** [comment]
Same as @cyrf0006 -- definitely have interest in contributing to such a project.

**Comment by granterogers** [comment]
Hi @rsignell-usgs , no plans in the near future to rewrite the toolbox for Python.

Aside from the financial implications, may I ask what you believe the benefit would
be in implementing this port?  It might be something to consider investing in the future.

Many Thanks!

**Comment by rsignell-usgs** [comment]
I only ask because the US Integrated Ocean Observing System and Oceans Observatories Initiative both are using python exclusively for their workflows from sensor data to science data.
