### ISSUE TITLE
QC on Preprocessing data

### ISSUE THREAD

**Issue by foxrowan** [socib/glider_toolbox#7]
Hi, I am trying to implement the Socib toolbox for delayed time with a Slocum G2 dataset.  I'm currently working though issues with first time set up of the toolbox.  I'm developing on Ubuntu 16, with Matlab R2017a.

I have an error while running lines 564-574 of process_glider_data_delayedtime.m.  Specifically, when I run line 568, it has an error:
Index exceeds matrix dimensions:
Error in performGriddedQC (line 124)
      for k=1:length(grid_qc_config.(tests{i}).passingParameters{j})

Because this is preprocessing data, why does line 568 call for the function performGriddedQC, which clearly calls for gridded data as input?  I realize this is the same for preprocessing data, processing data, as well as gridded data. performGriddedQC is quite clearly commented as for having gridded data as an input, however it's quite unclear what can be used as inputs here.

**Comment by granterogers** [comment]
Hi @foxrowan, thanks for the report.

Please bear in mind the QC implementation is not yet finalised (we are actively working on this) and as such the checks are designed with specific variables in mind.

I suspect that in your case, if you checkout configDataGriddingDataQC.m you might see some variables there setup for QC checking that are perhaps not present in your data.  Try removing these pertinent variables from your QC configuration and let me know how you get on.

**Comment by foxrowan** [comment]
Thanks @granterogers for your reply.  I think I will not worry about QC at all for the moment; if you are presently developing this, then there will be changes in the future that I will try to implement at that time.  I am still trying to get the toolbox working, and having very little success at the moment.  I will likely post future questions about adding extra sensors to the preprocessed data.

**Comment by granterogers** [comment]
Hi @foxrowan, I am working on a tutorial right now for users trying to get started.

If you don't mind a rough draft, send me an email to grogers@socib.es and I'll send you a copy.
I shall include some basic instructions for adding sensors.
